resources:
- ../../base/istory-app
- ../../base/istory-db

namespace: istory-dev

patches:
- path: patch-lb-annotations.yml
  target:
    kind: Service
    name: istory-app-lb
- path: patch-deploy.yml
  target:
    kind: Deployment
    name: istory-app-deploy

  # base/istory-app/istory-app-deploy.yml 내의 이미지 이름과 동일해야 변경됨
images:
- name: rapyuta1214/istory
  newName: rapyuta1214/istory
  newTag: "4"

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
